import { Items } from './items';


export const items:Items={
   "data":{
      "items":[
         {
            "_id":"609bc2b41a435e1b82658ddc",
            "images":[
               "assets/img/no_image_available.jpeg",
               "assets/img/no_image_available.jpeg",
               "assets/img/no_image_available.jpeg"
            ],
            "deleted":false,
            "deactivated":false,
            "status":"available",
            "availability":"public",
            "location":"london 000",
            "title":"test",
            "rent_rate":0,
            "owner_id":"609baf8b021a9f0dec4fd4e0",
            "uploaded_by_me":false,
            "order_id":"",
            "borrowed_by_me":false,
            "borrowed_status":""
         },
         {
            "_id":"6082cca86516922e8454834b",
            "images":[
               "public/uploads/image/1619184781846.jpg",
               "assets/img/no_image_available.jpeg",
               "assets/img/no_image_available.jpeg"
            ],
            "deleted":false,
            "deactivated":false,
            "status":"available",
            "availability":"public",
            "location":"London NW2",
            "title":"Drill",
            "rent_rate":0,
            "owner_id":"607ec8346516922e845482ae",
            "uploaded_by_me":false,
            "order_id":"",
            "borrowed_by_me":false,
            "borrowed_status":""
         },
         {
            "_id":"607ef9cf6516922e84548311",
            "images":[
               "public/uploads/image/1618934181155.jpg",
               "assets/img/no_image_available.jpeg",
               "assets/img/no_image_available.jpeg"
            ],
            "deleted":false,
            "deactivated":false,
            "status":"available",
            "availability":"public",
            "location":"London NW2",
            "title":"Cup",
            "rent_rate":0,
            "owner_id":"607e93696516922e845482ac",
            "uploaded_by_me":false,
            "order_id":"",
            "borrowed_by_me":false,
            "borrowed_status":""
         },
         {
            "_id":"607ef9696516922e8454830f",
            "images":[
               "public/uploads/image/1618934074319.jpg",
               "assets/img/no_image_available.jpeg",
               "assets/img/no_image_available.jpeg"
            ],
            "deleted":false,
            "deactivated":false,
            "status":"available",
            "availability":"public",
            "location":"London NW2",
            "title":"Tape",
            "rent_rate":0,
            "owner_id":"607e93696516922e845482ac",
            "uploaded_by_me":false,
            "order_id":"",
            "borrowed_by_me":false,
            "borrowed_status":""
         },
         {
            "_id":"607ef8f26516922e8454830c",
            "images":[
               "public/uploads/image/1618933669563.jpg",
               "assets/img/no_image_available.jpeg",
               "assets/img/no_image_available.jpeg"
            ],
            "deleted":false,
            "deactivated":false,
            "status":"available",
            "availability":"public",
            "location":"London NW2",
            "title":"Eurolive",
            "rent_rate":2,
            "owner_id":"607ecf7b6516922e845482bc",
            "uploaded_by_me":false,
            "order_id":"",
            "borrowed_by_me":false,
            "borrowed_status":""
         },
         {
            "_id":"607ef7216516922e84548309",
            "images":[
               "public/uploads/image/1618933500909.jpg",
               "assets/img/no_image_available.jpeg",
               "assets/img/no_image_available.jpeg"
            ],
            "deleted":false,
            "deactivated":false,
            "status":"available",
            "availability":"public",
            "location":"London NW2",
            "title":"hot cross buns",
            "rent_rate":3,
            "owner_id":"607ed9dd6516922e845482ce",
            "uploaded_by_me":false,
            "order_id":"",
            "borrowed_by_me":false,
            "borrowed_status":""
         },
         {
            "_id":"607ef6e96516922e84548307",
            "images":[
               "public/uploads/image/1618933441018.jpg",
               "assets/img/no_image_available.jpeg",
               "assets/img/no_image_available.jpeg"
            ],
            "deleted":false,
            "deactivated":false,
            "status":"available",
            "availability":"public",
            "location":"London NW2",
            "title":"Buns",
            "rent_rate":0,
            "owner_id":"607ed9dd6516922e845482ce",
            "uploaded_by_me":false,
            "order_id":"",
            "borrowed_by_me":false,
            "borrowed_status":""
         },
         {
            "_id":"607ef6996516922e84548305",
            "images":[
               "public/uploads/image/1618933338511.jpg",
               "public/uploads/image/1618933364716.jpg",
               "assets/img/no_image_available.jpeg"
            ],
            "deleted":false,
            "deactivated":false,
            "status":"available",
            "availability":"public",
            "location":"London NW2",
            "title":"Pie",
            "rent_rate":2,
            "owner_id":"607ec8346516922e845482ae",
            "uploaded_by_me":false,
            "order_id":"",
            "borrowed_by_me":false,
            "borrowed_status":""
         },
         {
            "_id":"607ef63a6516922e84548302",
            "images":[
               "public/uploads/image/1618933271656.JPG",
               "assets/img/no_image_available.jpeg",
               "assets/img/no_image_available.jpeg"
            ],
            "deleted":false,
            "deactivated":false,
            "status":"available",
            "availability":"public",
            "location":"London NW2",
            "title":"Dragon",
            "rent_rate":0,
            "owner_id":"607ec8346516922e845482ae",
            "uploaded_by_me":false,
            "order_id":"",
            "borrowed_by_me":false,
            "borrowed_status":""
         },
         {
            "_id":"607ef60f6516922e84548300",
            "images":[
               "public/uploads/image/1618933208350.jpg",
               "public/uploads/image/1618933219462.jpg",
               "public/uploads/image/1618933234942.jpg"
            ],
            "deleted":false,
            "deactivated":false,
            "status":"available",
            "availability":"public",
            "location":"London NW2",
            "title":"Ice axe",
            "rent_rate":2,
            "owner_id":"607ec8346516922e845482ae",
            "uploaded_by_me":false,
            "order_id":"",
            "borrowed_by_me":false,
            "borrowed_status":""
         },
         {
            "_id":"607ef5c46516922e845482fc",
            "images":[
               "public/uploads/image/1618933142727.JPG",
               "public/uploads/image/1618933152598.JPG",
               "public/uploads/image/1618933163550.JPG"
            ],
            "deleted":false,
            "deactivated":false,
            "status":"available",
            "availability":"public",
            "location":"London NW2",
            "title":"Cone spanner",
            "rent_rate":0,
            "owner_id":"607ece856516922e845482ba",
            "uploaded_by_me":false,
            "order_id":"",
            "borrowed_by_me":false,
            "borrowed_status":""
         },
         {
            "_id":"607eeae56516922e845482e8",
            "images":[
               "public/uploads/image/1618930348046.jpg",
               "assets/img/no_image_available.jpeg",
               "assets/img/no_image_available.jpeg"
            ],
            "deleted":false,
            "deactivated":false,
            "status":"available",
            "availability":"public",
            "location":"London NW2",
            "title":"Carpet cleaner",
            "rent_rate":20,
            "owner_id":"607ecf7b6516922e845482bc",
            "uploaded_by_me":false,
            "order_id":"",
            "borrowed_by_me":false,
            "borrowed_status":""
         },
         {
            "_id":"607eea0b6516922e845482e6",
            "images":[
               "public/uploads/image/1618929601999.JPG",
               "public/uploads/image/1618929658124.JPG",
               "assets/img/no_image_available.jpeg"
            ],
            "deleted":false,
            "deactivated":false,
            "status":"available",
            "availability":"public",
            "location":"London NW2",
            "title":"Pa system",
            "rent_rate":30,
            "owner_id":"607e93696516922e845482ac",
            "uploaded_by_me":false,
            "order_id":"",
            "borrowed_by_me":false,
            "borrowed_status":""
         },
         {
            "_id":"607ee6776516922e845482e3",
            "images":[
               "public/uploads/image/1618929201981.JPG",
               "public/uploads/image/1618929220210.JPG",
               "public/uploads/image/1618929232008.JPG"
            ],
            "deleted":false,
            "deactivated":false,
            "status":"available",
            "availability":"public",
            "location":"London NW2",
            "title":"Mafia Fancy dress",
            "rent_rate":10,
            "owner_id":"607ed9dd6516922e845482ce",
            "uploaded_by_me":false,
            "order_id":"",
            "borrowed_by_me":false,
            "borrowed_status":""
         },
         {
            "_id":"5fdfc7e7a01efb1b29875df5",
            "images":[
               "public/uploads/image/1608501187482.jpeg",
               "assets/img/no_image_available.jpeg",
               "assets/img/no_image_available.jpeg"
            ],
            "deleted":false,
            "deactivated":false,
            "status":"available",
            "availability":"public",
            "location":"London sw1",
            "title":"cakes",
            "rent_rate":10,
            "owner_id":"5fdfc6bea01efb1b29875df0",
            "uploaded_by_me":false,
            "order_id":"",
            "borrowed_by_me":false,
            "borrowed_status":""
         },
         {
            "_id":"5fdfc79fa01efb1b29875df3",
            "images":[
               "public/uploads/image/1608501109298.jpeg",
               "assets/img/no_image_available.jpeg",
               "assets/img/no_image_available.jpeg"
            ],
            "deleted":false,
            "deactivated":false,
            "status":"available",
            "availability":"public",
            "location":"London sw1",
            "title":"dog",
            "rent_rate":1,
            "owner_id":"5fdfc6bea01efb1b29875df0",
            "uploaded_by_me":false,
            "order_id":"",
            "borrowed_by_me":false,
            "borrowed_status":""
         },
         {
            "_id":"5fae28c0a01efb1b29875de3",
            "images":[
               "public/uploads/image/1605249164549.jpeg",
               "assets/img/no_image_available.jpeg",
               "assets/img/no_image_available.jpeg"
            ],
            "deleted":false,
            "deactivated":false,
            "status":"available",
            "availability":"public",
            "location":"London 000",
            "title":"lord of rings book",
            "rent_rate":3,
            "owner_id":"5f44b2be34c11f02255c482c",
            "uploaded_by_me":false,
            "order_id":"",
            "borrowed_by_me":false,
            "borrowed_status":""
         },
         {
            "_id":"5e4b79fd2fd08836a868e96e",
            "images":[
               "public/uploads/image/1582004645260.jpeg",
               "assets/img/no_image_available.jpeg",
               "assets/img/no_image_available.jpeg"
            ],
            "deleted":false,
            "deactivated":false,
            "status":"available",
            "location":"Bangalore 560",
            "title":"MTB",
            "rent_rate":10,
            "owner_id":"5cac88edae1a4371413caa3f",
            "uploaded_by_me":false,
            "order_id":"",
            "borrowed_by_me":false,
            "borrowed_status":""
         },
         {
            "_id":"5d5a754e83f34e345fc005a3",
            "images":[
               "public/uploads/image/1566209282595.jpg",
               "assets/img/no_image_available.jpeg",
               "assets/img/no_image_available.jpeg"
            ],
            "deleted":false,
            "deactivated":false,
            "status":"unavailable",
            "location":"Birmingham NW2",
            "title":"earth",
            "rent_rate":99,
            "owner_id":"5d5a713a83f34e345fc0059c",
            "uploaded_by_me":false,
            "order_id":"",
            "borrowed_by_me":false,
            "borrowed_status":""
         },
         {
            "_id":"5d42da6908d5ed2eb64798fa",
            "images":[
               "public/uploads/image/1564662337940.jpg",
               "assets/img/no_image_available.jpeg",
               "assets/img/no_image_available.jpeg"
            ],
            "deleted":false,
            "deactivated":false,
            "status":"available",
            "location":"Bangalore 560",
            "title":"Painting",
            "rent_rate":100,
            "owner_id":"5cac88edae1a4371413caa3f",
            "uploaded_by_me":false,
            "order_id":"",
            "borrowed_by_me":false,
            "borrowed_status":""
         },
         {
            "_id":"5d16557bd2575c2801bca286",
            "images":[
               "public/uploads/image/1561744706718.jpg",
               "public/uploads/image/1561744712009.jpg",
               "public/uploads/image/1561744717078.jpg"
            ],
            "deleted":false,
            "deactivated":false,
            "status":"available",
            "title":"Kayak",
            "rent_rate":20,
            "owner_id":"5d00f26430f21e20e6c70e55",
            "location":"London NW2",
            "uploaded_by_me":false,
            "order_id":"",
            "borrowed_by_me":false,
            "borrowed_status":""
         },
         {
            "_id":"5d16315cd2575c2801bca258",
            "images":[
               "public/uploads/image/1561735474264.JPG",
               "assets/img/no_image_available.jpeg",
               "assets/img/no_image_available.jpeg"
            ],
            "deleted":false,
            "deactivated":false,
            "status":"available",
            "title":"Karcher K4 Pressure Washer",
            "rent_rate":8.5,
            "owner_id":"5d00f26430f21e20e6c70e55",
            "location":"London",
            "uploaded_by_me":false,
            "order_id":"",
            "borrowed_by_me":false,
            "borrowed_status":""
         },
         {
            "_id":"5d1630c2d2575c2801bca252",
            "images":[
               "public/uploads/image/1561735293766.JPG",
               "public/uploads/image/1561735300520.JPG",
               "public/uploads/image/1561735305151.JPG"
            ],
            "deleted":false,
            "deactivated":false,
            "status":"available",
            "title":"Cordless Electric Mower - BOSCH",
            "rent_rate":10,
            "owner_id":"5d00f26430f21e20e6c70e55",
            "location":"London",
            "uploaded_by_me":false,
            "order_id":"",
            "borrowed_by_me":false,
            "borrowed_status":""
         },
         {
            "_id":"5d16306fd2575c2801bca24e",
            "images":[
               "public/uploads/image/1561735200986.JPG",
               "public/uploads/image/1561735204121.JPG",
               "assets/img/no_image_available.jpeg"
            ],
            "deleted":false,
            "deactivated":false,
            "status":"available",
            "title":"Cordless drill",
            "rent_rate":6,
            "owner_id":"5d00f26430f21e20e6c70e55",
            "location":"London",
            "uploaded_by_me":false,
            "order_id":"",
            "borrowed_by_me":false,
            "borrowed_status":""
         },
         {
            "_id":"5d162fc8d2575c2801bca247",
            "images":[
               "public/uploads/image/1561735076622.JPG",
               "assets/img/no_image_available.jpeg",
               "assets/img/no_image_available.jpeg"
            ],
            "deleted":false,
            "deactivated":false,
            "status":"available",
            "title":"How To Train your Dragon Hiccup outfit",
            "rent_rate":0,
            "owner_id":"5d00f26430f21e20e6c70e55",
            "location":"London",
            "uploaded_by_me":false,
            "order_id":"",
            "borrowed_by_me":false,
            "borrowed_status":""
         },
         {
            "_id":"5d162f94d2575c2801bca245",
            "images":[
               "public/uploads/image/1561735021887.JPG",
               "assets/img/no_image_available.jpeg",
               "assets/img/no_image_available.jpeg"
            ],
            "deleted":false,
            "deactivated":false,
            "status":"available",
            "title":"Spider Man Outfit Age 5-6",
            "rent_rate":0,
            "owner_id":"5d00f26430f21e20e6c70e55",
            "location":"London",
            "uploaded_by_me":false,
            "order_id":"",
            "borrowed_by_me":false,
            "borrowed_status":""
         },
         {
            "_id":"5d162f61d2575c2801bca243",
            "images":[
               "public/uploads/image/1561734926259.JPG",
               "public/uploads/image/1561734935086.JPG",
               "public/uploads/image/1561734940802.JPG"
            ],
            "deleted":false,
            "deactivated":false,
            "status":"available",
            "title":"Extra large catering size, stainless steel saucepan",
            "rent_rate":1,
            "owner_id":"5d00f26430f21e20e6c70e55",
            "location":"London",
            "uploaded_by_me":false,
            "order_id":"",
            "borrowed_by_me":false,
            "borrowed_status":""
         }
      ],
      "totalCount":27
   }
}